version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "smart-home-energy"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-xo6kdjxje917"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = false