AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Smart Home Energy Management System

Resources:
  # API Gateway
  ApiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: SmartHomeEnergyApi

  # Device Service
  DeviceService:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: ./device-service/
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DevicesTable
      Environment:
        Variables:
          DEVICES_TABLE: !Ref DevicesTable

  # API Gateway Resources and Methods for Device Service
  DevicesResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ApiGateway
      ParentId: !GetAtt ApiGateway.RootResourceId
      PathPart: 'devices'

  GetDevicesMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGateway
      ResourceId: !Ref DevicesResource
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${DeviceService.Arn}/invocations

  # Energy Service
  EnergyService:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: ./energy-service/
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref EnergyConsumptionTable
      Environment:
        Variables:
          ENERGY_TABLE: !Ref EnergyConsumptionTable
          DEVICE_SERVICE_URL: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/Prod"

  # API Gateway Resources and Methods for Energy Service
  EnergyResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ApiGateway
      ParentId: !GetAtt ApiGateway.RootResourceId
      PathPart: 'energy'

  ConsumptionResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ApiGateway
      ParentId: !Ref EnergyResource
      PathPart: 'consumption'

  RecordConsumptionMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGateway
      ResourceId: !Ref ConsumptionResource
      HttpMethod: POST
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${EnergyService.Arn}/invocations

  # User Service
  UserService:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: ./user-service/
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable
      Environment:
        Variables:
          USERS_TABLE: !Ref UsersTable
          DEVICE_SERVICE_URL: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/Prod"

  # API Gateway Resources and Methods for User Service
  UsersResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ApiGateway
      ParentId: !GetAtt ApiGateway.RootResourceId
      PathPart: 'users'

  CreateUserMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGateway
      ResourceId: !Ref UsersResource
      HttpMethod: POST
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${UserService.Arn}/invocations

  # DynamoDB Tables
  DevicesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Devices
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  EnergyConsumptionTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: EnergyConsumption
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Users
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  # S3 Bucket for Pact Files
  PactBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-pact-files"
      VersioningConfiguration:
        Status: Enabled

  # API Gateway Deployment
  ApiGatewayDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - GetDevicesMethod
      - RecordConsumptionMethod
      - CreateUserMethod
    Properties:
      RestApiId: !Ref ApiGateway
      StageName: Prod

Outputs:
  ApiUrl:
    Description: URL of the API Gateway endpoint
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/Prod/"

  PactBucketName:
    Description: Name of the S3 bucket for Pact files
    Value: !Ref PactBucket

  DeviceServiceFunction:
    Description: Device Service Lambda Function ARN
    Value: !GetAtt DeviceService.Arn

  EnergyServiceFunction:
    Description: Energy Service Lambda Function ARN
    Value: !GetAtt EnergyService.Arn

  UserServiceFunction:
    Description: User Service Lambda Function ARN
    Value: !GetAtt UserService.Arn